services:
  dataset-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataset-frontend
    restart: unless-stopped
    env_file:
      - .env.production
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dataset-rxlab.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.dataset-rxlab.entrypoints=websecure"
      - "traefik.http.routers.dataset-rxlab.tls=true"
      - "traefik.http.routers.dataset-rxlab.tls.certresolver=${TRAEFIK_CERTRESOLVER}"
      - "traefik.http.routers.dataset-rxlab.service=dataset-rxlab"
      - "traefik.http.services.dataset-rxlab.loadbalancer.server.port=3000"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
